name: Build, Pack, Push

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
    tags:
      # v.major.minor.patch[-suffix]
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-z]+'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  CONFIG: 'Release'
  TEST: true
  PUBLISH: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
  NUGET_URL: 'https://api.nuget.org/v3/index.json'
  BUILD_VERSION: '1.0.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Use tag as version number (without v)
    - name: Version
      if: ${{ env.PUBLISH == 'true' }}
      run: |
        TAG="${{ github.ref_name }}"
        echo "BUILD_VERSION=${TAG:1}" >> $GITHUB_ENV

    # https://github.com/actions/checkout
    - name: Checkout
      uses: actions/checkout@v3

    # https://github.com/actions/setup-dotnet
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2.1.1
      with:
        dotnet-version: '6.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build
            -p:Version=${{ env.BUILD_VERSION }}
            --configuration ${{ env.CONFIG }}
            --no-restore

    - name: Test
      if: ${{ env.TEST == 'true' }}
      run: dotnet test
            --no-build
            --no-restore
            --configuration ${{ env.CONFIG }}

    - name: Pack
      if: ${{ env.PUBLISH == 'true' }}
      run: |
        PROJECTS=./**/*.csproj
        shopt -s nullglob
        shopt -s globstar
        for p in $PROJECTS
        do
          echo "Packing $p"
          dotnet pack $p \
            --configuration ${{ env.CONFIG }} \
            --no-build \
            -p:Version=${{ env.BUILD_VERSION }} \
            -p:PackageVersion=${{ env.BUILD_VERSION }}
        done

    - name: NuGet Push
      if: ${{ env.PUBLISH == 'true' }}
      run: dotnet nuget push **/*.nupkg
            --source ${{ env.NUGET_URL }}
            --api-key ${{ secrets.NUGET_TOKEN }}
            --skip-duplicate
